# Generated by Django 4.0.6 on 2022-07-16 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_address_customer_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
