# Generated by Django 4.0.6 on 2022-07-16 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_airline_company_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='origin_country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country_id', to='base.country'),
        ),
    ]
