# Generated by Django 3.2.9 on 2022-07-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_flight_origin_country_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_company',
            old_name='Country_Id',
            new_name='country_ID',
        ),
        migrations.RenameField(
            model_name='airline_company',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='airline_company',
            old_name='User_ID',
            new_name='user_ID',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='airline_company',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
