# Generated by Django 3.2.9 on 2022-07-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220718_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
