# Generated by Django 3.2.9 on 2022-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_airline_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Departure_Time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Landing_Time',
            field=models.DateTimeField(),
        ),
    ]
