# Generated by Django 3.2.9 on 2022-07-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220719_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='Departure_Time',
            new_name='departure_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Destination_Country_Id',
            new_name='destination_country_id',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Landing_Time',
            new_name='landing_time',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Remaining_Tickets',
            new_name='remaining_tickets',
        ),
    ]
