# Generated by Django 3.2.9 on 2022-07-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220720_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='Customer_Id',
            new_name='customer_Id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Flight_Id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight_Id',
            field=models.OneToOneField(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.flight'),
        ),
    ]
