# Generated by Django 3.2.9 on 2022-07-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_airline_company_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_company',
            name='country_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_ID', to='base.country'),
        ),
    ]
