# Generated by Django 3.2.9 on 2022-07-20 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_airline_company_country_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='User_Id',
            new_name='user_ID',
        ),
        migrations.RemoveField(
            model_name='airline_company',
            name='createdTime',
        ),
    ]
