# Generated by Django 3.2.9 on 2022-07-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220720_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='user_ID',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_Id',
            new_name='user_id',
        ),
    ]
