# Generated by Django 3.2.9 on 2022-07-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20220720_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_Id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_Id',
            new_name='flight_id',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight_id', 'customer_id')},
        ),
    ]
