# Generated by Django 3.2.9 on 2022-07-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20220720_2346'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='countries',
        ),
    ]
