# Generated by Django 3.2.9 on 2022-07-20 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_alter_country_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_company',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country'),
        ),
        migrations.AlterField(
            model_name='airline_company',
            name='name',
            field=models.CharField(max_length=52, unique=True),
        ),
        migrations.AlterField(
            model_name='airline_company',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='airline_company',
            table='airline_companies',
        ),
    ]
