# Generated by Django 3.2.9 on 2022-07-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220721_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='credit_Card_no',
            new_name='credit_card_no',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_No',
            new_name='phone_no',
        ),
    ]
