# Generated by Django 3.2.9 on 2022-08-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airline_company_id',
            new_name='the_airline_company_id',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
