# Generated by Django 3.2.9 on 2022-08-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220811_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='the_airline_company_id',
            new_name='airline_company_id',
        ),
    ]
