# Generated by Django 3.2.9 on 2022-08-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_the_airline_company_id_flight_airline_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_role',
            name='try_time',
            field=models.DateField(default=False),
        ),
    ]
